### PR TITLE
added query-string and simple parameter-based landing pages

### PR DESCRIPTION
**Pull request by cwhunt**
This gives a landing for floors. What's the easiest way to have it also land with computer info?

### CODE REVIEW

**Comment by BryceV** [comment]
Nice! Is this for #3? I was using react-router but this might be a better method. You want to have the landing page floor 1/computers? I think the activeResource in the App state should already be pointed to computers (the "1" state?).

**Comment by cwhunt** [comment]
> Nice! Is this for #3? I was using react-router but this might be a better method. You want to have the landing page floor 1/computers? I think the activeResource in the App state should already be pointed to computers (the "1" state?).

Yes. I was thinking react-router may be more than what's needed here. We could do an "r" parameter for resources but we at least need what the digital signs will load (parameter for floor with the computers resource loaded). It looks to me like the default resource is seats (1). It may be sufficient to set it to 2 when there's an 'f' parameter. I'll create a pull request for that and you can look it over.

**Comment by BryceV** [comment]
Oh yes, it looks like at this commit it was set to seats (1). I am trying to get this merge to work with http://localhost:3000/?f=4 (as a test) to no avail. What URLs are you testing with?

**Comment by cwhunt** [comment]
> Oh yes, it looks like at this commit it was set to seats (1). I am trying to get this merge to work with http://localhost:3000/?f=4 (as a test) to no avail. What URLs are you testing with?

It uses the cardinal number which matches the floorNames (i.e., "4th"). http://localhost:3000/?f=4th

**Comment by BryceV** [comment]
Got it. I committed a check for a valid 'f' in the URL. Also, this should update for each floor change (for copy/pasting availability). So I will look at moving some of this to the state.

**Comment by cwhunt** [comment]
> Got it. I committed a check for a valid 'f' in the URL. Also, this should update for each floor change (for copy/pasting availability). So I will look at moving some of this to the state.

Sounds good.

**Pull request merged**
