### PR TITLE
not working: spaces API

### PR DESCRIPTION
**Pull request by cwhunt**
This is not necessarily to merge with master but to take a look at. I put in some code for #4 but the data doesn't seem to be passing down through the prop when it gets loaded. spaces.json has the data from r25-35.json and the new information from the fishbowls.

### CODE REVIEW

**Comment by BryceV** [comment]
Ok. So does spaces.json have mock data or is it ready for production use? After looking at the code, it might be an AJAX problem. I would only test to see if (this.props.roomData[floorName]) exists before running. First function pass roomData is usually undefined in my experience.

**Comment by BryceV** [comment]
Oh, also the fishbowl data looks like it was put into the "1st" floor array? Rooms like 216k are only listed on the 2nd floor.

**Comment by cwhunt** [comment]
> Ok. So does spaces.json have mock data or is it ready for production use? After looking at the code, it might be an AJAX problem. I would only test to see if (this.props.roomData[floorName]) exists before running. First function pass roomData is usually undefined in my experience.

I put in some mock data into the real API call. After today there's probably enough production data for testing but I put one mock entry in the real API call (8-9am). The problem seems to be, as you mentioned in the other comment, that I put the data into "1st" and was looking on the 2nd floor. I fixed that and now I'm seeing the data. I'll see if I can abandon this pull request and try another.

**Comment by cwhunt** [comment]
> Oh, also the fishbowl data looks like it was put into the "1st" floor array? Rooms like 216k are only listed on the 2nd floor.

Oops, missed this and it seems it may be the problem. Thanks!

**Pull request closed without merging**
